package com.mrt.backend;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.*;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpMethod;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.cors.*;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import java.sql.Statement;

@SpringBootApplication
public class MrtBackendApplication {
 public static void main(String[] args){SpringApplication.run(MrtBackendApplication.class,args);}
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean SecurityFilterChain security(HttpSecurity h)throws Exception{return h.csrf(c->c.disable()).cors(c->{}).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers(HttpMethod.OPTIONS,"/**").permitAll().requestMatchers("/api/auth/**","/api/products/**","/api/categories/**","/api/reviews/product/**").permitAll().anyRequest().permitAll()).build();}
 @Bean CorsConfigurationSource cors(@Value("${mrt.cors-origins}")String origins){CorsConfiguration c=new CorsConfiguration();c.setAllowedOrigins(Arrays.asList(origins.split(",")));c.setAllowedMethods(List.of("*"));c.setAllowedHeaders(List.of("*"));c.setAllowCredentials(true);UrlBasedCorsConfigurationSource s=new UrlBasedCorsConfigurationSource();s.registerCorsConfiguration("/**",c);return s;}
}

@RestController
@RequestMapping("/api")
class MrtController {
 private final JdbcTemplate db; private final PasswordEncoder enc; private final Map<String,Long> tokens=new ConcurrentHashMap<>(); private final String adminEmail,adminPassword;
 MrtController(JdbcTemplate db,PasswordEncoder enc,@Value("${mrt.admin-email}")String ae,@Value("${mrt.admin-password}")String ap){this.db=db;this.enc=enc;adminEmail=ae;adminPassword=ap;}
 Map<String,Object> ok(Object d){return Map.of("success",true,"data",d);} Map<String,Object> fail(String m){return Map.of("success",false,"message",m);}
 long insertId(String sql,Object... args){KeyHolder kh=new GeneratedKeyHolder();db.update(conn->{var ps=conn.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);for(int i=0;i<args.length;i++)ps.setObject(i+1,args[i]);return ps;},kh);Number n=kh.getKey();return n==null?0:n.longValue();} long id(Map<String,Object>b,String k){return Long.parseLong(String.valueOf(b.get(k)));}

 @PostMapping("/auth/register") Map<String,Object> register(@RequestBody Map<String,Object>b){String e=String.valueOf(b.get("email")).toLowerCase();if(!db.queryForList("select id from users where email=?",e).isEmpty())return fail("Email already registered");long id=insertId("insert into users(name,email,password_hash,phone) values(?,?,?,?)",b.get("name"),e,enc.encode(String.valueOf(b.get("password"))),b.get("phone"));String t=UUID.randomUUID().toString();tokens.put(t,id);return ok(Map.of("token",t,"user",db.queryForMap("select id,name,email,phone,role,status from users where id=?",id)));}
 @PostMapping("/auth/login") Map<String,Object> login(@RequestBody Map<String,Object>b){String e=String.valueOf(b.get("email")).toLowerCase(),p=String.valueOf(b.get("password"));if(e.equals(adminEmail)&&p.equals(adminPassword)){List<Map<String,Object>>x=db.queryForList("select id from users where email=?",e);long id=x.isEmpty()?insertId("insert into users(name,email,password_hash,role) values(?,?,?,'SUPER_ADMIN')","MRT Admin",e,enc.encode(p)):((Number)x.get(0).get("id")).longValue();String t=UUID.randomUUID().toString();tokens.put(t,id);return ok(Map.of("token",t,"user",db.queryForMap("select id,name,email,role,status from users where id=?",id)));}List<Map<String,Object>>x=db.queryForList("select * from users where email=? and status='ACTIVE'",e);if(x.isEmpty()||!enc.matches(p,String.valueOf(x.get(0).get("password_hash"))))return fail("Invalid email or password");long id=((Number)x.get(0).get("id")).longValue();String t=UUID.randomUUID().toString();tokens.put(t,id);return ok(Map.of("token",t,"user",db.queryForMap("select id,name,email,phone,role,status from users where id=?",id)));}
 @PostMapping("/auth/logout") Map<String,Object> logout(@RequestHeader(value="Authorization",required=false)String h){if(h!=null)tokens.remove(h.replace("Bearer ",""));return ok("Logged out");}
 @GetMapping("/auth/me") Map<String,Object> me(@RequestHeader(value="Authorization",required=false)String h){Long id=h==null?null:tokens.get(h.replace("Bearer ",""));return id==null?fail("Not authenticated"):ok(db.queryForMap("select id,name,email,phone,role,status from users where id=?",id));}

 @GetMapping("/products") Map<String,Object> products(@RequestParam(required=false)String search){String q="select p.*,c.name category from products p left join categories c on c.id=p.category_id where p.status='ACTIVE'";if(search!=null&&!search.isBlank())q+=" and lower(p.name) like '%"+search.toLowerCase().replace("'","''")+"%'";return ok(db.queryForList(q+" order by p.featured desc,p.id desc"));}
 @GetMapping("/products/{id}") Map<String,Object> product(@PathVariable long id){return ok(db.queryForMap("select p.*,c.name category from products p left join categories c on c.id=p.category_id where p.id=?",id));}
 @GetMapping("/products/{id}/images") Map<String,Object> images(@PathVariable long id){return ok(db.queryForList("select * from product_images where product_id=? order by sort_order,id",id));}
 @GetMapping("/categories") Map<String,Object> cats(){return ok(db.queryForList("select * from categories where active=true order by name"));}
 @GetMapping("/categories/{id}") Map<String,Object> cat(@PathVariable long id){return ok(db.queryForMap("select * from categories where id=?",id));}

 private Long auth(String h){return h==null?null:tokens.get(h.replace("Bearer ",""));}
 @GetMapping("/cart") Map<String,Object> cart(@RequestHeader(value="Authorization",required=false)String h){Long u=auth(h);if(u==null)return fail("Authentication required");return ok(db.queryForList("select ci.*,p.name,p.price,p.image_url,p.stock from cart_items ci join carts c on c.id=ci.cart_id join products p on p.id=ci.product_id where c.user_id=?",u));}
 @PostMapping("/cart/items") Map<String,Object> addCart(@RequestHeader(value="Authorization",required=false)String h,@RequestBody Map<String,Object>b){Long u=auth(h);if(u==null)return fail("Authentication required");long p=id(b,"productId");int q=Integer.parseInt(String.valueOf(b.getOrDefault("quantity",1)));List<Map<String,Object>>c=db.queryForList("select id from carts where user_id=?",u);long cid=c.isEmpty()?insertId("insert into carts(user_id) values(?)",u):((Number)c.get(0).get("id")).longValue();List<Map<String,Object>>i=db.queryForList("select id,quantity from cart_items where cart_id=? and product_id=?",cid,p);if(i.isEmpty())db.update("insert into cart_items(cart_id,product_id,quantity) values(?,?,?)",cid,p,q);else db.update("update cart_items set quantity=quantity+? where id=?",q,i.get(0).get("id"));return cart(h);}
 @PutMapping("/cart/items/{id}") Map<String,Object> updateCart(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id,@RequestBody Map<String,Object>b){Long u=auth(h);if(u==null)return fail("Authentication required");db.update("update cart_items set quantity=? where id=? and cart_id in(select id from carts where user_id=?)",b.get("quantity"),id,u);return cart(h);}
 @DeleteMapping("/cart/items/{id}") Map<String,Object> delCart(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){Long u=auth(h);if(u==null)return fail("Authentication required");db.update("delete from cart_items where id=? and cart_id in(select id from carts where user_id=?)",id,u);return cart(h);}
 @GetMapping("/wishlist") Map<String,Object> wishlist(@RequestHeader(value="Authorization",required=false)String h){Long u=auth(h);if(u==null)return fail("Authentication required");return ok(db.queryForList("select w.*,p.name,p.price,p.image_url from wishlists w join products p on p.id=w.product_id where w.user_id=?",u));}
 @PostMapping("/wishlist/items/{id}") Map<String,Object> wish(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){Long u=auth(h);if(u==null)return fail("Authentication required");if(db.queryForList("select id from wishlists where user_id=? and product_id=?",u,id).isEmpty())db.update("insert into wishlists(user_id,product_id) values(?,?)",u,id);return wishlist(h);}
 @DeleteMapping("/wishlist/items/{id}") Map<String,Object> unwish(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){Long u=auth(h);if(u==null)return fail("Authentication required");db.update("delete from wishlists where user_id=? and product_id=?",u,id);return wishlist(h);}

 @PostMapping("/custom-orders") Map<String,Object> custom(@RequestHeader(value="Authorization",required=false)String h,@RequestBody Map<String,Object>b){Long u=auth(h);db.update("insert into custom_orders(user_id,name,email,phone,product,quantity,details) values(?,?,?,?,?,?,?)",u,b.get("name"),b.get("email"),b.get("phone"),b.get("product"),b.get("qty"),b.get("details"));return ok("Custom order submitted");}
 @GetMapping("/orders") Map<String,Object> orders(@RequestHeader(value="Authorization",required=false)String h){Long u=auth(h);if(u==null)return fail("Authentication required");return ok(db.queryForList("select * from orders where user_id=? order by created_at desc",u));}
 @GetMapping("/orders/{id}") Map<String,Object> order(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){Long u=auth(h);if(u==null)return fail("Authentication required");return ok(db.queryForMap("select * from orders where id=? and user_id=?",id,u));}
 @GetMapping("/reviews/product/{id}") Map<String,Object> reviews(@PathVariable long id){return ok(db.queryForList("select r.*,u.name from reviews r join users u on u.id=r.user_id where r.product_id=? and r.status='APPROVED'",id));}
 @PostMapping("/reviews") Map<String,Object> review(@RequestHeader(value="Authorization",required=false)String h,@RequestBody Map<String,Object>b){Long u=auth(h);if(u==null)return fail("Authentication required");db.update("insert into reviews(user_id,product_id,rating,title,body) values(?,?,?,?,?)",u,b.get("productId"),b.get("rating"),b.get("title"),b.get("body"));return ok("Review submitted");}
 @GetMapping("/user/profile") Map<String,Object> profile(@RequestHeader(value="Authorization",required=false)String h){Long u=auth(h);return u==null?fail("Authentication required"):ok(db.queryForMap("select id,name,email,phone,role,status from users where id=?",u));}
 @PutMapping("/user/profile") Map<String,Object> profileUpdate(@RequestHeader(value="Authorization",required=false)String h,@RequestBody Map<String,Object>b){Long u=auth(h);if(u==null)return fail("Authentication required");db.update("update users set name=?,phone=? where id=?",b.get("name"),b.get("phone"),u);return profile(h);}

 @GetMapping("/admin/dashboard") Map<String,Object> dashboard(){return ok(Map.of("products",count("products"),"orders",count("orders"),"customers",count("users"),"revenue",db.queryForObject("select coalesce(sum(total),0) from orders",Object.class)));}
 @GetMapping("/admin/products") Map<String,Object> adminProducts(){return ok(db.queryForList("select p.*,c.name category from products p left join categories c on c.id=p.category_id order by p.id desc"));}
 @PostMapping("/admin/products") Map<String,Object> createProduct(@RequestBody Map<String,Object>b){db.update("insert into products(name,price,original_price,image_url,material,weight,dimensions,description,stock,featured,badge,occasion) values(?,?,?,?,?,?,?,?,?,?,?,?)",b.get("name"),b.get("price"),b.get("originalPrice"),b.get("image"),b.get("material"),b.get("weight"),b.get("dimensions"),b.get("description"),b.getOrDefault("stock",0),b.getOrDefault("featured",false),b.get("badge"),b.get("occasion"));return adminProducts();}
 @PutMapping("/admin/products/{id}") Map<String,Object> editProduct(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update products set name=?,price=?,original_price=?,image_url=?,stock=?,description=?,status=? where id=?",b.get("name"),b.get("price"),b.get("originalPrice"),b.get("image"),b.getOrDefault("stock",0),b.get("description"),b.getOrDefault("status","ACTIVE"),id);return product(id);}
 @DeleteMapping("/admin/products/{id}") Map<String,Object> removeProduct(@PathVariable long id){db.update("delete from product_images where product_id=?",id);db.update("delete from products where id=?",id);return ok("Deleted");}
 @PatchMapping("/admin/products/{id}/status") Map<String,Object> status(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update products set status=? where id=?",b.get("status"),id);return product(id);}
 @PostMapping("/admin/products/{id}/images") Map<String,Object> addImage(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("insert into product_images(product_id,image_url,sort_order) values(?,?,?)",id,b.get("imageUrl"),b.getOrDefault("sortOrder",0));return images(id);}
 @DeleteMapping("/admin/products/{id}/images/{imageId}") Map<String,Object> removeImage(@PathVariable long id,@PathVariable long imageId){db.update("delete from product_images where id=? and product_id=?",imageId,id);return images(id);}
 @GetMapping("/admin/categories") Map<String,Object> adminCats(){return cats();}
 @PostMapping("/admin/categories") Map<String,Object> addCat(@RequestBody Map<String,Object>b){db.update("insert into categories(name,image_url,description) values(?,?,?)",b.get("name"),b.get("imageUrl"),b.get("description"));return cats();}
 @PutMapping("/admin/categories/{id}") Map<String,Object> editCat(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update categories set name=?,image_url=?,description=?,active=? where id=?",b.get("name"),b.get("imageUrl"),b.get("description"),b.getOrDefault("active",true),id);return cats();}
 @DeleteMapping("/admin/categories/{id}") Map<String,Object> removeCat(@PathVariable long id){db.update("delete from categories where id=?",id);return ok("Deleted");}
 @GetMapping("/admin/inventory") Map<String,Object> inventory(){return ok(db.queryForList("select id,name,stock,status from products order by stock"));}@GetMapping("/admin/inventory/low-stock") Map<String,Object> low(){return ok(db.queryForList("select id,name,stock from products where stock<=10 order by stock"));}
 @GetMapping("/admin/orders") Map<String,Object> allOrders(){return ok(db.queryForList("select * from orders order by created_at desc"));}@PatchMapping("/admin/orders/{id}/status") Map<String,Object> orderStatus(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update orders set status=? where id=?",b.get("status"),id);return ok("Updated");}@PatchMapping("/admin/orders/{id}/payment") Map<String,Object> payStatus(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update orders set payment_status=? where id=?",b.get("paymentStatus"),id);return ok("Updated");}
 @GetMapping("/admin/customers") Map<String,Object> customers(){return ok(db.queryForList("select id,name,email,phone,role,status,created_at from users order by id desc"));}@GetMapping("/admin/custom-orders") Map<String,Object> adminCustom(){return ok(db.queryForList("select * from custom_orders order by created_at desc"));}@GetMapping("/admin/quotations") Map<String,Object> quotes(){return ok(db.queryForList("select * from quotations order by created_at desc"));}@GetMapping("/admin/reviews") Map<String,Object> adminReviews(){return ok(db.queryForList("select * from reviews order by created_at desc"));}@GetMapping("/admin/offers") Map<String,Object> offers(){return ok(db.queryForList("select * from offers order by id desc"));}@GetMapping("/admin/notifications") Map<String,Object> notifications(){return ok(db.queryForList("select * from notifications order by created_at desc"));}@GetMapping("/admin/users") Map<String,Object> admins(){return ok(db.queryForList("select id,name,email,phone,role,status,created_at from users order by id desc"));}@GetMapping("/admin/settings") Map<String,Object> settings(){return ok(db.queryForList("select * from admin_settings"));}@GetMapping("/admin/activity-log") Map<String,Object> activity(){return ok(db.queryForList("select * from activity_log order by created_at desc"));}@GetMapping("/admin/analytics/overview") Map<String,Object> overview(){return dashboard();}@GetMapping("/admin/analytics/revenue") Map<String,Object> ar(){return ok(db.queryForList("select cast(created_at as date) day,sum(total) revenue from orders group by cast(created_at as date) order by day desc"));}@GetMapping("/admin/analytics/orders") Map<String,Object> ao(){return ok(db.queryForList("select status,count(*) count from orders group by status"));}@GetMapping("/admin/analytics/products") Map<String,Object> ap(){return ok(db.queryForList("select id,name,stock,rating,review_count from products"));}@GetMapping("/admin/analytics/customers") Map<String,Object> ac(){return ok(db.queryForList("select u.id,u.name,count(o.id) orders,coalesce(sum(o.total),0) total_spent from users u left join orders o on o.user_id=u.id group by u.id,u.name"));}

  @PostMapping("/orders") Map<String,Object> createOrder(@RequestHeader(value="Authorization",required=false)String h,@RequestBody Map<String,Object>b){Long u=auth(h);if(u==null)return fail("Authentication required");String no="MRT-"+System.currentTimeMillis();db.update("insert into orders(user_id,order_number,total,shipping_address) values(?,?,?,?)",u,no,b.getOrDefault("total",0),b.get("shippingAddress"));Map<String,Object> created=db.queryForMap("select * from orders where order_number=?",no);created.put("items",b.getOrDefault("items",List.of()));return ok(created);}
 @PostMapping("/orders/{id}/cancel") Map<String,Object> cancelOrder(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){Long u=auth(h);if(u==null)return fail("Authentication required");db.update("update orders set status='Cancelled' where id=? and user_id=?",id,u);return order(h,id);}
 @GetMapping("/orders/{id}/tracking") Map<String,Object> tracking(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){Long u=auth(h);if(u==null)return fail("Authentication required");return ok(db.queryForMap("select id,order_number,status,payment_status,created_at from orders where id=? and user_id=?",id,u));}
 @PostMapping("/payments/create") Map<String,Object> paymentCreate(@RequestHeader(value="Authorization",required=false)String h,@RequestBody Map<String,Object>b){if(auth(h)==null)return fail("Authentication required");return ok(Map.of("paymentId","PAY-"+System.currentTimeMillis(),"status","CREATED","amount",b.get("amount"))); }
 @PostMapping("/payments/verify") Map<String,Object> paymentVerify(@RequestHeader(value="Authorization",required=false)String h,@RequestBody Map<String,Object>b){if(auth(h)==null)return fail("Authentication required");return ok(Map.of("verified",true));}
 @GetMapping("/payments/{orderId}") Map<String,Object> payment(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long orderId){if(auth(h)==null)return fail("Authentication required");return ok(db.queryForMap("select id,order_number,payment_status,total from orders where id=?",orderId));}
 @GetMapping("/notifications") Map<String,Object> userNotifications(@RequestHeader(value="Authorization",required=false)String h){Long u=auth(h);if(u==null)return fail("Authentication required");return ok(db.queryForList("select * from notifications where user_id=? order by created_at desc",u));}
 @PatchMapping("/notifications/{id}/read") Map<String,Object> userNotificationRead(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){Long u=auth(h);if(u==null)return fail("Authentication required");db.update("update notifications set read_flag=true where id=? and user_id=?",id,u);return ok("Read");}
 @PatchMapping("/notifications/read-all") Map<String,Object> userNotificationsReadAll(@RequestHeader(value="Authorization",required=false)String h){Long u=auth(h);if(u==null)return fail("Authentication required");db.update("update notifications set read_flag=true where user_id=?",u);return ok("All read");}
 @GetMapping("/quotations") Map<String,Object> userQuotes(@RequestHeader(value="Authorization",required=false)String h){Long u=auth(h);if(u==null)return fail("Authentication required");return ok(db.queryForList("select * from quotations where user_id=? order by created_at desc",u));}
 @GetMapping("/quotations/{id}") Map<String,Object> userQuote(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){Long u=auth(h);if(u==null)return fail("Authentication required");return ok(db.queryForMap("select * from quotations where id=? and user_id=?",id,u));}
 @PostMapping("/quotations/{id}/accept") Map<String,Object> acceptQuote(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){Long u=auth(h);if(u==null)return fail("Authentication required");db.update("update quotations set status='Accepted' where id=? and user_id=?",id,u);return userQuote(h,id);}

 @GetMapping("/admin/orders/{id}") Map<String,Object> adminOrder(@PathVariable long id){return ok(db.queryForMap("select * from orders where id=?",id));}
 @PostMapping("/admin/orders/{id}/refund") Map<String,Object> refund(@PathVariable long id){db.update("update orders set status='Returned',payment_status='Refunded' where id=?",id);return adminOrder(id);}
 @GetMapping("/admin/custom-orders/{id}") Map<String,Object> adminCustomOne(@PathVariable long id){return ok(db.queryForMap("select * from custom_orders where id=?",id));}
 @PatchMapping("/admin/custom-orders/{id}/status") Map<String,Object> customStatus(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update custom_orders set status=? where id=?",b.get("status"),id);return adminCustomOne(id);}
 @PostMapping("/admin/custom-orders/{id}/quote") Map<String,Object> customQuote(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("insert into quotations(custom_order_id,amount,notes,status) values(?,?,?,'Sent')",id,b.get("amount"),b.get("notes"));db.update("update custom_orders set status='Quoted' where id=?",id);return ok("Quotation sent");}
 @GetMapping("/admin/reviews/{id}") Map<String,Object> adminReview(@PathVariable long id){return ok(db.queryForMap("select * from reviews where id=?",id));}
 @PatchMapping("/admin/reviews/{id}/status") Map<String,Object> adminReviewStatus(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update reviews set status=? where id=?",b.get("status"),id);return adminReview(id);}
 @DeleteMapping("/admin/reviews/{id}") Map<String,Object> adminReviewDelete(@PathVariable long id){db.update("delete from reviews where id=?",id);return ok("Deleted");}
 @PostMapping("/admin/offers") Map<String,Object> adminOfferCreate(@RequestBody Map<String,Object>b){db.update("insert into offers(code,title,discount_type,discount_value,active) values(?,?,?,?,?)",b.get("code"),b.get("title"),b.get("discountType"),b.get("discountValue"),b.getOrDefault("active",true));return offers();}
 @PutMapping("/admin/offers/{id}") Map<String,Object> adminOfferUpdate(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update offers set code=?,title=?,discount_type=?,discount_value=?,active=? where id=?",b.get("code"),b.get("title"),b.get("discountType"),b.get("discountValue"),b.getOrDefault("active",true),id);return offers();}
 @DeleteMapping("/admin/offers/{id}") Map<String,Object> adminOfferDelete(@PathVariable long id){db.update("delete from offers where id=?",id);return ok("Deleted");}
 @PatchMapping("/admin/offers/{id}/status") Map<String,Object> adminOfferStatus(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update offers set active=? where id=?",b.get("active"),id);return offers();}
 @PatchMapping("/admin/notifications/{id}/read") Map<String,Object> adminNotificationRead(@PathVariable long id){db.update("update notifications set read_flag=true where id=?",id);return ok("Read");}
 @PatchMapping("/admin/notifications/read-all") Map<String,Object> adminNotificationsReadAll(){db.update("update notifications set read_flag=true");return ok("All read");}
 @PostMapping("/admin/users") Map<String,Object> adminUserCreate(@RequestBody Map<String,Object>b){db.update("insert into users(name,email,password_hash,role) values(?,?,?,?)",b.get("name"),b.get("email"),enc.encode(String.valueOf(b.get("password"))),b.getOrDefault("role","MANAGER"));return admins();}
 @PutMapping("/admin/users/{id}") Map<String,Object> adminUserUpdate(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update users set name=?,email=?,role=? where id=?",b.get("name"),b.get("email"),b.get("role"),id);return admins();}
 @DeleteMapping("/admin/users/{id}") Map<String,Object> adminUserDelete(@PathVariable long id){db.update("delete from users where id=?",id);return ok("Deleted");}
 @PatchMapping("/admin/users/{id}/status") Map<String,Object> adminUserStatus(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update users set status=? where id=?",b.get("status"),id);return admins();}
 @PutMapping("/admin/settings") Map<String,Object> adminSettingsSave(@RequestBody Map<String,Object>b){b.forEach((k,v)->db.update("merge into admin_settings(setting_key,setting_value) key(setting_key) values(?,?)",k,String.valueOf(v)));return settings();}
 @PutMapping("/admin/settings/password") Map<String,Object> adminPassword(@RequestHeader(value="Authorization",required=false)String h,@RequestBody Map<String,Object>b){Long u=auth(h);if(u==null)return fail("Authentication required");db.update("update users set password_hash=? where id=?",enc.encode(String.valueOf(b.get("newPassword"))),u);return ok("Password updated");}
 private long count(String t){return Optional.ofNullable(db.queryForObject("select count(*) from "+t,Long.class)).orElse(0L);}

 @GetMapping("/products/featured") Map<String,Object> featured(){return ok(db.queryForList("select p.*,c.name category from products p left join categories c on c.id=p.category_id where p.status='ACTIVE' and p.featured=true order by p.id desc"));}
 @GetMapping("/products/offers") Map<String,Object> productOffers(){return ok(db.queryForList("select p.*,c.name category from products p left join categories c on c.id=p.category_id where p.status='ACTIVE' and p.original_price is not null and p.original_price>p.price order by p.id desc"));}
 @GetMapping("/categories/{id}/image") Map<String,Object> categoryImage(@PathVariable long id){return ok(db.queryForMap("select id,image_url from categories where id=?",id));}
 @DeleteMapping("/cart") Map<String,Object> clearCart(@RequestHeader(value="Authorization",required=false)String h){Long u=auth(h);if(u==null)return fail("Authentication required");db.update("delete from cart_items where cart_id in(select id from carts where user_id=?)",u);return cart(h);}
 @GetMapping("/admin/dashboard/revenue") Map<String,Object> dashboardRevenue(){return ar();}
 @GetMapping("/admin/dashboard/orders") Map<String,Object> dashboardOrders(){return ao();}
 @GetMapping("/admin/dashboard/categories") Map<String,Object> dashboardCategories(){return ok(db.queryForList("select c.id,c.name,count(p.id) product_count from categories c left join products p on p.category_id=c.id group by c.id,c.name order by product_count desc"));}
 @GetMapping("/admin/customers/{id}") Map<String,Object> customer(@PathVariable long id){return ok(db.queryForMap("select id,name,email,phone,role,status,created_at from users where id=?",id));}
 @GetMapping("/admin/customers/{id}/orders") Map<String,Object> customerOrders(@PathVariable long id){return ok(db.queryForList("select * from orders where user_id=? order by created_at desc",id));}
 @PatchMapping("/admin/customers/{id}/status") Map<String,Object> customerStatus(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update users set status=? where id=?",b.get("status"),id);return customer(id);}
 @GetMapping("/admin/quotations/{id}") Map<String,Object> adminQuotation(@PathVariable long id){return ok(db.queryForMap("select * from quotations where id=?",id));}
 @PostMapping("/admin/quotations") Map<String,Object> adminQuotationCreate(@RequestBody Map<String,Object>b){db.update("insert into quotations(custom_order_id,user_id,amount,notes,status) values(?,?,?,?,?)",b.get("customOrderId"),b.get("userId"),b.get("amount"),b.get("notes"),b.getOrDefault("status","Draft"));return quotes();}
 @PutMapping("/admin/quotations/{id}") Map<String,Object> adminQuotationUpdate(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update quotations set amount=?,notes=?,status=? where id=?",b.get("amount"),b.get("notes"),b.getOrDefault("status","Draft"),id);return adminQuotation(id);}
 @PatchMapping("/admin/quotations/{id}/status") Map<String,Object> adminQuotationStatus(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("update quotations set status=? where id=?",b.get("status"),id);return adminQuotation(id);}
}
