package in.mrt.controller;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import java.util.*;
@RestController @RequestMapping("/api/admin")
public class AdminController {
 private final JdbcTemplate db; public AdminController(JdbcTemplate db){this.db=db;}
 private static final Map<String,String> TABLES=Map.of("products","products","categories","categories","inventory","products","orders","orders","customers","users","custom-orders","custom_orders","quotations","quotations","reviews","reviews","offers","offers","notifications","notifications","users","users","activity-log","activity_log");
 @GetMapping("/dashboard") public Map<String,Object> dashboard(){return Map.of("products",count("products"),"customers",count("users"),"orders",count("orders"),"revenue",db.queryForObject("select coalesce(sum(total),0) from orders where status<>'CANCELLED'",Double.class));}
 @GetMapping("/dashboard/revenue") public List<Map<String,Object>> revenue(){return db.queryForList("select date_format(created_at,'%Y-%m') month,coalesce(sum(total),0) revenue from orders group by date_format(created_at,'%Y-%m') order by month");}
 @GetMapping("/dashboard/orders") public List<Map<String,Object>> dashOrders(){return db.queryForList("select * from orders order by created_at desc limit 20");}
 @GetMapping("/dashboard/categories") public List<Map<String,Object>> dashCategories(){return db.queryForList("select c.id,c.name,count(p.id) product_count from categories c left join products p on p.category_id=c.id group by c.id,c.name");}
 private long count(String t){return db.queryForObject("select count(*) from "+t,Long.class);}
 @GetMapping("/{resource}") public List<Map<String,Object>> list(@PathVariable String resource){String t=TABLES.get(resource);if(t==null)throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND);return db.queryForList("select * from "+t+" order by id desc");}
 @GetMapping("/{resource}/{id}") public Map<String,Object> get(@PathVariable String resource,@PathVariable Long id){String t=TABLES.get(resource);if(t==null)throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND);return db.queryForMap("select * from "+t+" where id=?",id);}
 @PostMapping("/products") public Map<String,Object> addProduct(@RequestBody Map<String,Object>b){db.update("insert into products(name,category_id,sku,price,original_price,stock,description,material,weight,dimensions,image_url,featured) values(?,?,?,?,?,?,?,?,?,?,?,?)",b.get("name"),b.get("categoryId"),b.get("sku"),b.get("price"),b.get("originalPrice"),b.getOrDefault("stock",0),b.get("description"),b.get("material"),b.get("weight"),b.get("dimensions"),b.get("imageUrl"),b.getOrDefault("featured",false));return db.queryForMap("select * from products where id=last_insert_id()");}
 @PutMapping("/products/{id}") public Map<String,Object> updateProduct(@PathVariable Long id,@RequestBody Map<String,Object>b){db.update("update products set name=?,category_id=?,price=?,original_price=?,stock=?,description=?,material=?,weight=?,dimensions=?,image_url=?,featured=? where id=?",b.get("name"),b.get("categoryId"),b.get("price"),b.get("originalPrice"),b.get("stock"),b.get("description"),b.get("material"),b.get("weight"),b.get("dimensions"),b.get("imageUrl"),b.getOrDefault("featured",false),id);return get("products",id);}
 @DeleteMapping("/products/{id}") public Map<String,Object> deleteProduct(@PathVariable Long id){db.update("delete from products where id=?",id);return Map.of("success",true);}
 @PatchMapping("/products/{id}/status") public Map<String,Object> productStatus(@PathVariable Long id,@RequestBody Map<String,Object>b){db.update("update products set status=? where id=?",b.get("status"),id);return get("products",id);}
 @PostMapping("/categories") public Map<String,Object> addCategory(@RequestBody Map<String,Object>b){db.update("insert into categories(name,description,image_url) values(?,?,?)",b.get("name"),b.get("description"),b.get("imageUrl"));return db.queryForMap("select * from categories where id=last_insert_id()");}
 @PutMapping("/categories/{id}") public Map<String,Object> updateCategory(@PathVariable Long id,@RequestBody Map<String,Object>b){db.update("update categories set name=?,description=?,image_url=? where id=?",b.get("name"),b.get("description"),b.get("imageUrl"),id);return get("categories",id);}
 @DeleteMapping("/categories/{id}") public Map<String,Object> deleteCategory(@PathVariable Long id){db.update("delete from categories where id=?",id);return Map.of("success",true);}
 @PatchMapping("/inventory/{productId}") public Map<String,Object> inventory(@PathVariable Long productId,@RequestBody Map<String,Object>b){db.update("update products set stock=? where id=?",b.get("stock"),productId);return get("inventory",productId);}
 @PatchMapping("/orders/{id}/status") public Map<String,Object> orderStatus(@PathVariable Long id,@RequestBody Map<String,Object>b){db.update("update orders set status=? where id=?",b.get("status"),id);return get("orders",id);}
 @PatchMapping("/orders/{id}/payment") public Map<String,Object> payment(@PathVariable Long id,@RequestBody Map<String,Object>b){db.update("update orders set payment_status=? where id=?",b.get("paymentStatus"),id);return get("orders",id);}
 @PatchMapping("/customers/{id}/status") public Map<String,Object> customerStatus(@PathVariable Long id,@RequestBody Map<String,Object>b){db.update("update users set status=? where id=?",b.get("status"),id);return get("customers",id);}
 @PatchMapping("/reviews/{id}/status") public Map<String,Object> reviewStatus(@PathVariable Long id,@RequestBody Map<String,Object>b){db.update("update reviews set status=? where id=?",b.get("status"),id);return get("reviews",id);}
 @DeleteMapping("/reviews/{id}") public Map<String,Object> deleteReview(@PathVariable Long id){db.update("delete from reviews where id=?",id);return Map.of("success",true);}
 @GetMapping("/analytics/overview") public Map<String,Object> analytics(){return dashboard();}
 @GetMapping("/analytics/revenue") public List<Map<String,Object>> analyticsRevenue(){return revenue();}
 @GetMapping("/analytics/orders") public List<Map<String,Object>> analyticsOrders(){return db.queryForList("select status,count(*) count,sum(total) total from orders group by status");}
 @GetMapping("/analytics/products") public List<Map<String,Object>> analyticsProducts(){return db.queryForList("select p.id,p.name,p.stock,coalesce(sum(oi.quantity),0) units_sold from products p left join order_items oi on oi.product_id=p.id group by p.id,p.name,p.stock");}
 @GetMapping("/analytics/customers") public List<Map<String,Object>> analyticsCustomers(){return db.queryForList("select u.id,u.name,u.email,count(o.id) orders,coalesce(sum(o.total),0) spend from users u left join orders o on o.user_id=u.id group by u.id,u.name,u.email");}
 @PostMapping("/offers") public Map<String,Object> addOffer(@RequestBody Map<String,Object>b){db.update("insert into offers(title,code,discount_type,discount_value,min_order_value,status) values(?,?,?,?,?,?)",b.get("title"),b.get("code"),b.get("discountType"),b.get("discountValue"),b.getOrDefault("minOrderValue",0),b.getOrDefault("status","ACTIVE"));return db.queryForMap("select * from offers where id=last_insert_id()");}
 @PutMapping("/offers/{id}") public Map<String,Object> updateOffer(@PathVariable Long id,@RequestBody Map<String,Object>b){db.update("update offers set title=?,code=?,discount_type=?,discount_value=?,min_order_value=?,status=? where id=?",b.get("title"),b.get("code"),b.get("discountType"),b.get("discountValue"),b.get("minOrderValue"),b.get("status"),id);return get("offers",id);}
 @DeleteMapping("/offers/{id}") public Map<String,Object> deleteOffer(@PathVariable Long id){db.update("delete from offers where id=?",id);return Map.of("success",true);}
 @PatchMapping("/offers/{id}/status") public Map<String,Object> offerStatus(@PathVariable Long id,@RequestBody Map<String,Object>b){db.update("update offers set status=? where id=?",b.get("status"),id);return get("offers",id);}
 @GetMapping("/settings") public Map<String,Object> settings(){return Map.of("storeName","MRT Metal Mart","currency","INR","shippingThreshold",2000);}
 @PutMapping("/settings") public Map<String,Object> saveSettings(@RequestBody Map<String,Object>b){return b;}
 @GetMapping("/activity-log") public List<Map<String,Object>> activity(){return db.queryForList("select * from activity_log order by created_at desc");}
}