CREATE TABLE IF NOT EXISTS users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(120) NOT NULL, email VARCHAR(180) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, phone VARCHAR(40), role VARCHAR(30) NOT NULL DEFAULT 'USER',
 status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categories (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(160) NOT NULL UNIQUE, description TEXT, image_url TEXT,
 status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS products (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(200) NOT NULL, category_id BIGINT, sku VARCHAR(80) UNIQUE,
 price DECIMAL(12,2) NOT NULL DEFAULT 0, original_price DECIMAL(12,2), stock INT NOT NULL DEFAULT 0,
 description TEXT, material VARCHAR(120), weight VARCHAR(80), dimensions VARCHAR(120), image_url TEXT,
 status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', featured BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS cart_items (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, product_id BIGINT NOT NULL, quantity INT NOT NULL,
 UNIQUE KEY uq_cart(user_id,product_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS wishlist_items (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, product_id BIGINT NOT NULL,
 UNIQUE KEY uq_wishlist(user_id,product_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS orders (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
 payment_status VARCHAR(40) NOT NULL DEFAULT 'PENDING', total DECIMAL(12,2) NOT NULL DEFAULT 0,
 shipping_address TEXT, tracking_number VARCHAR(120), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS order_items (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, order_id BIGINT NOT NULL, product_id BIGINT, product_name VARCHAR(200),
 quantity INT NOT NULL, price DECIMAL(12,2) NOT NULL, FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS reviews (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, product_id BIGINT NOT NULL,
 rating INT NOT NULL, comment TEXT, status VARCHAR(30) DEFAULT 'PUBLISHED', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS custom_orders (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT, name VARCHAR(160), email VARCHAR(180), phone VARCHAR(40),
 description TEXT, quantity INT DEFAULT 1, status VARCHAR(40) DEFAULT 'NEW', quoted_amount DECIMAL(12,2),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS quotations (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, custom_order_id BIGINT, user_id BIGINT, amount DECIMAL(12,2),
 notes TEXT, status VARCHAR(40) DEFAULT 'DRAFT', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS offers (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(180), code VARCHAR(80) UNIQUE, discount_type VARCHAR(30),
 discount_value DECIMAL(12,2), min_order_value DECIMAL(12,2) DEFAULT 0, starts_at TIMESTAMP, ends_at TIMESTAMP,
 status VARCHAR(30) DEFAULT 'ACTIVE');
CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT, title VARCHAR(180), message TEXT,
 is_read BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS activity_log (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT, action VARCHAR(255), entity_type VARCHAR(80),
 entity_id BIGINT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admin_users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL UNIQUE, permissions TEXT,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
