CREATE TABLE IF NOT EXISTS users (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,email VARCHAR(180) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,
 phone VARCHAR(40),role VARCHAR(30) NOT NULL DEFAULT 'USER',status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS categories (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL UNIQUE,image_url VARCHAR(1000),
 description VARCHAR(1000),active BOOLEAN DEFAULT TRUE,status VARCHAR(30) DEFAULT 'ACTIVE'
);
CREATE TABLE IF NOT EXISTS products (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255) NOT NULL,category_id BIGINT,sku VARCHAR(80),
 price DECIMAL(12,2) NOT NULL,original_price DECIMAL(12,2),rating DECIMAL(3,2) DEFAULT 0,
 review_count INT DEFAULT 0,image_url VARCHAR(1000),material VARCHAR(120),weight VARCHAR(120),
 dimensions VARCHAR(160),description VARCHAR(4000),stock INT DEFAULT 0,status VARCHAR(30) DEFAULT 'ACTIVE',
 featured BOOLEAN DEFAULT FALSE,badge VARCHAR(80),occasion VARCHAR(160),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS product_images (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,product_id BIGINT NOT NULL,image_url VARCHAR(1000) NOT NULL,sort_order INT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS carts (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL UNIQUE,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS cart_items (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,cart_id BIGINT NOT NULL,product_id BIGINT NOT NULL,quantity INT NOT NULL,
 UNIQUE(cart_id,product_id)
);
CREATE TABLE IF NOT EXISTS wishlists (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,product_id BIGINT NOT NULL,
 UNIQUE(user_id,product_id)
);
CREATE TABLE IF NOT EXISTS orders (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT,order_number VARCHAR(50) NOT NULL UNIQUE,
 status VARCHAR(40) DEFAULT 'Processing',payment_status VARCHAR(40) DEFAULT 'Pending',
 total DECIMAL(12,2) DEFAULT 0,shipping_address VARCHAR(2000),tracking_number VARCHAR(120),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS order_items (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,order_id BIGINT NOT NULL,product_id BIGINT NOT NULL,
 product_name VARCHAR(255) NOT NULL,quantity INT NOT NULL,unit_price DECIMAL(12,2) NOT NULL
);
CREATE TABLE IF NOT EXISTS reviews (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,product_id BIGINT NOT NULL,rating INT NOT NULL,
 title VARCHAR(255),body VARCHAR(2000),comment VARCHAR(2000),status VARCHAR(30) DEFAULT 'PENDING',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS custom_orders (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT,name VARCHAR(120) NOT NULL,email VARCHAR(180) NOT NULL,
 phone VARCHAR(40),product VARCHAR(255),quantity INT,details VARCHAR(4000),description VARCHAR(4000),
 budget DECIMAL(12,2),status VARCHAR(40) DEFAULT 'New',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS quotations (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,custom_order_id BIGINT,user_id BIGINT,amount DECIMAL(12,2),
 notes VARCHAR(3000),status VARCHAR(40) DEFAULT 'Draft',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS offers (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(80) UNIQUE,title VARCHAR(255),discount_type VARCHAR(30),
 discount_value DECIMAL(12,2),min_order_value DECIMAL(12,2) DEFAULT 0,status VARCHAR(30) DEFAULT 'ACTIVE',
 active BOOLEAN DEFAULT TRUE,starts_at TIMESTAMP,ends_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT,title VARCHAR(255),message VARCHAR(2000),
 read_flag BOOLEAN DEFAULT FALSE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS activity_log (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,actor VARCHAR(180),action VARCHAR(500),type VARCHAR(40),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS admin_settings (setting_key VARCHAR(120) PRIMARY KEY,setting_value VARCHAR(4000));
